### ISSUE TITLE
No Action Plan Template Lookup From New Button on Related List

### ISSUE THREAD

**Issue by Eric-Schumann** [SalesforceLabs/ActionPlansV4#43]
**Describe the bug**
When clicking on the New button from the Action Plan related list on a record page, the screen doesn't include the Action Plan Template Lookup Field.  

**To Reproduce**
1. Go to a record page that includes the Action Plan related list.
2. Click on New button on the Action Plan related list.
3. At the top of the page, the Action Plan Template Lookup is missing.

**Expected behavior**

**Screenshots**
From Action Plan Related List > New:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/5678630/173146684-f6ecb5fc-4437-4f6b-9a22-49d06d54f0d2.png">

From Record Page > Create New Action Plan:
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/5678630/173146819-d10e26c7-74c4-4440-8e59-36e2d6a1dfee.png">

**Environment (please complete the following information):**
 - OS: Windows
 
 - Browser: Chrome
 - 
 - Action Plans Version (e.g. 4.0.1) (See Setup > Installed Packages)

 - Salesforce UI
Lightning Experience
 
 - Org Edition
Enterprise Edition

**Comment by dschach** [comment]
It looks like it's performing as intended. The instructions are to remove the standard New button from the page layout, using the custom button instead. 

> Expand "Buttons" section, clear the "New" checkbox and move "Create Account Action Plan" to the Selected buttons.

The second screenshot looks like it is working correctly.

If you want to make an Action Plan from a Template, you can also go to the Template and create it from there, but right now that second screenshot looks like you've set up the custom object correctly.

I'm working on releasing a new version in the next week that will address some of the reported bugs, but I'm having trouble setting it up so that users of the latest released version can upgrade. For now, install the latest version from AppExchange over your current version. You should have 4.2.1.
